### ISSUE TITLE
Homepage development

### ISSUE THREAD

**Issue by byzyk** [webkwik/static-webpage#4]
Develop the static homepage based on [the following design](https://www.figma.com/proto/RYPI3F3BDXZF7dUIbha20krF/Gravity?node-id=0%3A1&viewport=183%2C247%2C0.442317&scaling=min-zoom).

## Assets

[Download](https://www.dropbox.com/s/i9o1y15vzhidwzi/Gravity.fig?dl=0) the assets here.

## Tasks

- [x] #5 header
- [x] hero slider
- [x] "We solve" section
- [x] services slider
- [x] "Our works" section
- [x] "Testimonials" section
- [x] "Our clients" section
- [x] footer
